In [59]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

In [60]:
pd.__version__

'2.2.2'

In [61]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")
# data = pd.read_csv("data/laptops.csv")

In [62]:
df.head(10)

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   
5  MSI Crosshair 17 C12VF-264XES Intel Core i7-12...    New     MSI   
6  Lenovo Thinkpad E14 Gen 4 AMD Ryzen 5 5625U/8G...    New  Lenovo   
7  ASUS VivoBook 15 F515JA-EJ2882W Intel Core i7-...    New    Asus   
8  Medion Akoya E15415 Intel Core i5-10210U/8GB/2...    New  Medion   
9  HP Victus 16-d1038ns Intel Core i7-12700H/16GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   
5   Crosshair  Intel Core i7   32     1000          SSD  RTX 4060    17.3   
6    ThinkPad    AMD Ryzen 5    8      256          SSD       NaN    14.0   
7    VivoBook  Intel Core i7    8      512          SSD       NaN    15.6   
8       Akoya  Intel Core i5    8      256          SSD       NaN    15.6   
9      Victus  Intel Core i7   16      512          SSD  RTX 3050    16.1   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01  
5    No      1699.00  
6    No       909.00  
7    No       809.01  
8    No       519.00  
9    No      1149.00

how many records?

In [63]:
df.shape[0]

2160

How many laptop brands are presented in the dataset

In [64]:
df['Brand'].nunique()

27

How many columns in the dataset have missing values?

In [65]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

What's the maximum final price of Dell notebooks in the dataset?

In [66]:
df.groupby('Brand')['Final Price'].max()

Brand
Acer                3691.00
Alurin               869.00
Apple               3849.00
Asus                5758.14
Deep Gaming         1639.01
Dell                3936.00
Denver               329.95
Dynabook Toshiba    1805.01
Gigabyte            3799.00
HP                  5368.77
Innjoo               431.38
Jetwing              469.27
LG                  2399.00
Lenovo              5018.14
MSI                 7150.47
Medion              3799.00
Microsoft           3747.91
Millenium           2312.71
PcCom               1949.90
Primux               599.41
Prixton              329.95
Razer               4999.01
Realme               999.00
Samsung             3699.01
Thomson              436.56
Toshiba              799.00
Vant                1217.01
Name: Final Price, dtype: float64

In [67]:
df.groupby('Brand')['Final Price'].agg(['mean', 'max', 'min'])

mean      max      min
Brand                                          
Acer              1001.285766  3691.00   264.14
Alurin             484.701379   869.00   239.00
Apple             1578.227672  3849.00   299.00
Asus              1269.380699  5758.14   239.25
Deep Gaming       1505.377500  1639.01  1334.00
Dell              1153.839881  3936.00   379.00
Denver             329.950000   329.95   329.95
Dynabook Toshiba   999.197895  1805.01   397.29
Gigabyte          1698.488958  3799.00   799.00
HP                 952.628478  5368.77   210.14
Innjoo             347.888333   431.38   251.40
Jetwing            469.270000   469.27   469.27
LG                1730.028438  2399.00   609.04
Lenovo            1087.723880  5018.14   239.00
MSI               1913.451006  7150.47   444.19
Medion             905.331875  3799.00   246.89
Microsoft         1595.543247  3747.91   599.01
Millenium         1976.845000  2312.71  1640.98
PcCom             1606.762917  1949.90  1049.00
Primux             339.618750   599.41   208.99
Prixton            292.280000   329.95   246.95
Razer             3265.701622  4999.01  1232.74
Realme             999.000000   999.00   999.00
Samsung           1595.511364  3699.01   365.90
Thomson            316.860000   436.56   201.05
Toshiba            799.000000   799.00   799.00
Vant              1047.455455  1217.01   632.00

Q6. Median value of Screen  
1. Find the median value of Screen column in the dataset.  
2. Next, calculate the most frequent value of the same Screen column.  
3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.  
4. Now, calculate the median value of Screen once again.  
Has it changed?

In [68]:
df['Screen'].median()

15.6

In [69]:
mode_screen = df['Screen'].mode()

In [70]:
df['Screen'].fillna(mode_screen).median()

15.6

In [71]:
df['Screen_2'] = df['Screen'].fillna(mode_screen)

In [72]:
print(df['Screen'].median())
print(df['Screen_2'].median())


15.6
15.6


Q7. Sum of weights  
1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns RAM, Storage, Screen.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.  
What's the sum of all the elements of the result?


In [77]:
injoo_df = df[df['Brand'] == 'Innjoo']

In [78]:
injoo_df = injoo_df[['RAM', 'Storage', 'Screen']]

injoo_df

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [80]:
X = injoo_df.values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [84]:
#transpose X
XTX= X.T.dot(X)

In [85]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [86]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [92]:
w = (XTX_inv @ X.T) @ y

In [93]:
w

array([45.58076606,  0.42783519, 45.29127938])

In [94]:
sum(w)

91.2998806299557